spring.application.name=insightdesk

spring.datasource.url=jdbc:postgresql://localhost:5432/insightdesk
spring.datasource.username=aylinminayi
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true