apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: insightdesk
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi